### PR TITLE
Add: quiz-result-page

### PR DESCRIPTION
**Pull request by gauravsinhaweb**

### CODE REVIEW

**Review by JuvitaSaini09 — APPROVED** [review]
your code looks clean

**Review by anshulraheja — APPROVED** [review]
The result page is great but I can see that by clicking on the options the color is changing to blue, I believe on the result page, the option to select should be disabled, rest everything is fine.

**Review by malaykhakhar — APPROVED** [review]
The code is clean and no suggestions. You can merge it.

**Comment by gauravsinhaweb** [comment]
> The result page is great but I can see that by clicking on the options the color is changing to blue, I believe on the result page, the option to select should be disabled, rest everything is fine.

It's a functionality, I haven't added js yet. I will do that.

**Pull request merged**
